apiVersion: v1
kind: Service
metadata:
  name: paicoin-service
spec:
  # ports:
  # - port: 18566
  #   name: rpc
  clusterIP: None
  selector:
    app: paicoin-live

---
apiVersion: v1
kind: Service
metadata:
  name: cpuminer-service
spec:
  clusterIP: None
  selector:
    app: cpuminer-live
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: paicoin-config-map
  labels:
    app: paicoin-live
data:
  paicoin.conf: |-
    server=1
    bantime=1
    daemon=0
    rpcuser=paicoin
    rpcpassword=PAI
    # rpcport=4002 # use default 18566
    rpcallowip=0.0.0.0/0
    rpcbind=0.0.0.0
    testnet=1
    txindex=1
    onlynet=ipv4
    listenonion=0
    listen=1
    printtoconsole=1
    datadir=/root/data
    # dnsseed=0
    # connect=0
    maxtipage = 86400 # this is default = 60 days in seconds

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paicoin-node
spec:
  selector:
    matchLabels:
      app: paicoin-live
  serviceName: paicoin-service
  replicas: 3
  template:
    metadata:
      labels:
        app: paicoin-live
    spec:
      volumes:
      - name: paicoin-datadir
        emptyDir: {}
      - name: paicoin-config
        configMap:
          name: paicoin-config-map
          items:
            - key: paicoin.conf
              path: paicoin.conf
      containers:
      - name: paicoin-node
        image: hybrid-consensus:0.16.1
        imagePullPolicy: Never
        ports:
        - containerPort: 18566
          name: rpc
        - containerPort: 18567
          name: connect
        command: ["/bin/bash", "-c"]
        # args: ["paicoind"]
        args:
        - sleep 2;
          CONNECTS=$(busybox nslookup paicoin-service | grep $(hostname -d) | grep -v $(hostname) | awk '{print $3}' | while read line || [[ -n $line ]]; do echo -n ' -connect='$line; done);
          echo $CONNECTS;
          paicoind $CONNECTS;
        volumeMounts:
          - mountPath: /root/data
            name: paicoin-datadir
          - mountPath: /root/.paicoin
            name: paicoin-config
      # initContainers:
      # - name: init-paicoin-service
      #   image: busybox:1.28
      #   command: ['sh', '-c', "until nslookup paicoin-service; do echo waiting for paicoin-service; sleep 2; done"]

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cpuminer
spec:
  selector:
    matchLabels:
      app: cpuminer-live
  serviceName: cpuminer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cpuminer-live
    spec:
      containers:
      - name: cpuminer
        image: cpuminer
        imagePullPolicy: Never
        command: ["/bin/bash", "-c"]
        args:
        - ./minerd -a sha256d -o http://172.18.0.7:18566 -O paicoin:PAI -P 