apiVersion: v1
kind: Service
metadata:
  name: paicoin-service
  labels:
    app: paicoin-live
spec:
  # ports:
  # - port: 80
  #   name: web
  clusterIP: None
  selector:
    app: paicoin-live

---

apiVersion: v1
data:
  paicoin.conf: |-
    server=1
    bantime=1
    daemon=0
    rpcuser=paicoin
    rpcpassword=PAI
    rpcport=4002
    rpcallowip=0.0.0.0/0
    rpcbind=0.0.0.0
    testnet=1
    txindex=1
    onlynet=ipv4
    listenonion=0
    listen=1
    printtoconsole=1
    datadir=/root/data
    # dnsseed=0
    # connect=0
kind: ConfigMap
metadata:
  name: paicoin-config-map

---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: paicoin-data-pv-volume
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/paicoin-data"

# ---

# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: paicoin-data-pv-claim
# spec:
#   storageClassName: manual 
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

# ---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: paicoin-node
spec:
  selector:
    matchLabels:
      app: paicoin-live
  serviceName: paicoin-service
  replicas: 3
  template:
    metadata:
      labels:
        app: paicoin-live
    spec:
      volumes:
      # - name: paicoin-data-pv-storage
      #   persistentVolumeClaim:
      #     claimName: paicoin-data-pv-claim
      - name: paicoin-datadir
        emptyDir: {}
      - name: paicoin-config
        configMap:
          name: paicoin-config-map
          items:
            - key: paicoin.conf
              path: paicoin.conf
      containers:
      - name: paicoin-node
        image: hybrid-consensus:0.16.1
        imagePullPolicy: Never
        command: ["/bin/bash", "-c"]
        # args: ["paicoind"]
        args: ["sleep 2 && CONNECTS=$(busybox nslookup paicoin-service | grep $(hostname -d) | grep -v $(hostname) | awk '{print $3}' | while read line || [[ -n $line ]]; do echo -n ' -connect='$line; done) && echo $CONNECTS && paicoind $CONNECTS"]
        volumeMounts:
          - mountPath: /root/data
            # name: paicoin-data-pv-storage
            name: paicoin-datadir
          - mountPath: /root/.paicoin
            name: paicoin-config
  # volumeClaimTemplates:
  # - metadata:
  #     name: paicoin-datadir
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: manual
  #     resources:
  #       requests:
  #         storage: 1Gi